---
apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: myapp-enterprise
spec:
  title: Gitlab Enterprise
  icon: https://about.gitlab.com/ico/apple-touch-icon-144x144.png
  releaseNotes: |
    Icon and application URL changed
  ports:
    - serviceName: "gitlab-nginx-ingress-controller"
      servicePort: 443
      localPort: 443
      applicationUrl: "http://gitlab.materiography.com"
    statusInformers:
      - deployment/gitlab-gitlab-exporter
      - deployment/gitlab-gitlab-runner
      - deployment/gitlab-gitlab-shell
      - deployment/gitlab-minio
      - deployment/gitlab-nginx-ingress-controller
      - deployment/gitlab-nginx-ingress-default-backend
      - deployment/gitlab-prometheus-server
      - deployment/gitlab-registry
      - deployment/gitlab-sidekiq-all-in-1-v1
      - deployment/gitlab-task-runner
      - deployment/gitlab-unicorn
      - statefulset/gitlab-gitaly
      - statefulset/gitlab-postgresql
      - statefulset/gitlab-redis-master