apiVersion: troubleshoot.replicated.com/v1beta1
kind: Collector
metadata:
  name: collector-sample
spec:
  collectors:
    - clusterInfo: {}
    - clusterResources: {}
    - logs:
        selector:
          - release=gitlab
        namespace: repl{{ Namespace }}
        name: gitlab-logs
        limits:
          maxAge: 30d
          maxLines: 10000